site_name: Mehmet Gurdal
site_description: Mehmet Gurdal resume.
site_author: Mehmet Gürdal
site_url: https://mgurdal.github.io


nav:
    - Introduction: index.md
    - Projects : projects.md
    - Professional Life: professional.md
    - Education: education.md

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/mgurdal
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/mgurdal_
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/mgurdal
    - icon: fontawesome/brands/kaggle
      link: https://www.kaggle.com/anticode

theme:
  name: 'material'
  logo: assets/images/logo.png
  favicon: assets/images/favicon.ico

extra_css:
    - assets/css/extra.css

favicon: assets/images/favicon.ico

google_analytics:
  - UA-163254669-1
  - auto
